services:
  init-app-database:
    image: mariadb:11.6
    depends_on:
      app-database:
        condition: service_healthy
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_SCHEMA}"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    command: 
      - "exit 0"
    networks:
      - app-network

  init-database-postgres:
    image: postgres:17
    depends_on:
      database-postgres:
        condition: service_healthy
    command: 
      - "exit 0"
    networks:
      - app-network

  app-database:
    image: mariadb:11.6
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      retries: 10
      timeout: 10s
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_SCHEMA}"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"

  app-postgres:
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U '${DATABASE_USERNAME}' -d ${DATABASE_SCHEMA} -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    environment:
      POSTGRES_DB: "${DATABASE_SCHEMA}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    networks:
      - app-network

networks:
  app-network: