
name: Test Package

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    environment: ${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up environment variables
        run: |
          cat << EOF > ./.env
          JWT_SECRET_KEY=a9w083j9w873h789w2
          AUTO_VERIFY_USERS=0
          DISABLE_REHASHING=0
          MYSQL_ROOT_PASSWORD=jlka7sw47aSD234
          DATABASE_PORT=3324
          DATABASE_USERNAME=awuiyh34ygsd
          DATABASE_PASSWORD=3ui45hiyuawer
          DATABASE_SCHEMA=appdb
          EOF
          ls -lah ./.env

      - name: Start Database
        run: |
          ./start.sh

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Run tests
        run: npm test
