
name: Test Package

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up environment variables
        run: |
          echo "$ENV_FILE" > .env

      - name: Start Database
        run: |
          ./start.sh

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Run tests
        run: npm test
